local module = {
	{
		Name = "Custom - String Manipulation #1",
		Description = 'Create a module to replace "er" to "ing" in a string',
		Explanations = {
			Function = 'The function the module returns should take a string parameter.',
                        Behaviour = 'The function should replace all mentions of the string "er" with "ing".'
		},
		Module = "stringReplacement",
		Color = Color3.fromRGB(0, 255, 0),
	},
}

return module
